/**
 * JavaScript and Node.js SDK for Auth0 Fine Grained Authorization (FGA)
 *
 * API version: 0.1
 * Website: <https://fga.dev>
 * Documentation: <https://docs.fga.dev>
 * Support: <https://discord.gg/8naAwJfWN6>
 * License: [MIT](https://github.com/auth0-lab/fga-js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by [OpenAPI Generator](https://openapi-generator.tech). DO NOT EDIT.
 */


import * as nock from "nock";
import { CallResult } from "@openfga/sdk/dist/common";
import { ClientCredentialsConfig } from "@openfga/sdk/dist/credentials";
import {
  FgaApiInternalError,
  FgaApiNotFoundError,
  FgaApiRateLimitExceededError,
  FgaApiValidationError,
  FgaApiAuthenticationError,
  AuthorizationModel,
  CheckResponse,
  ErrorCode,
  ExpandResponse,
  ListObjectsResponse,
  ReadAuthorizationModelResponse,
  ReadAuthorizationModelsResponse,
  ReadChangesResponse,
  ReadResponse,
  TupleKey,
  TupleOperation,
  WriteAuthorizationModelRequest,
} from "@openfga/sdk";

import {
  Auth0FgaApi,
  Configuration,
  GetDefaultRetryParams,
} from "../";

nock.disableNetConnect();

const AUTH0_FGA_ENVIRONMENT = "playground";
const AUTH0_FGA_STORE_ID = "test-random-store-id";
const AUTH0_FGA_CLIENT_ID = "some-random-id";
const AUTH0_FGA_CLIENT_SECRET = "this-is-very-secret";

const baseConfig = {
  storeId: AUTH0_FGA_STORE_ID,
  environment: AUTH0_FGA_ENVIRONMENT,
  clientId: AUTH0_FGA_CLIENT_ID,
  clientSecret: AUTH0_FGA_CLIENT_SECRET,
};

const defaultConfiguration = new Configuration(baseConfig);
const AUTH0_FGA_API_TOKEN_ISSUER = (defaultConfiguration.credentials as { config: ClientCredentialsConfig }).config.apiTokenIssuer;

const nocks = {
  tokenExchange: (
    apiTokenIssuer: string,
    accessToken = "test-token",
    expiresIn = 300
  ) => {
    return nock(`https://${apiTokenIssuer}`).post("/oauth/token").reply(200, {
      access_token: accessToken,
      expires_in: expiresIn,
    });
  },
  readAuthorizationModels: (
    storeId: string,
    basePath = defaultConfiguration.getBasePath(),
    authorizationModels: AuthorizationModel[] = [{ id: "some-id", type_definitions: [] }],
  ) => {
    return nock(basePath)
      .get(`/stores/${storeId}/authorization-models`)
      .reply(200, {
        authorization_models: authorizationModels,
      } as ReadAuthorizationModelsResponse);
  },
  check: (
    storeId: string,
    tuple: TupleKey,
    basePath = defaultConfiguration.getBasePath(),
  ) => {
    return nock(basePath)
      .post(`/stores/${storeId}/check`)
      .reply(200, {
        allowed: true,
      } as CheckResponse);
  },
  write: (
    storeId: string,
    basePath = defaultConfiguration.getBasePath(),
    responseBody: object | { code: string, message: string } = {},
    statusCode = 204,
  ) => {
    return nock(basePath)
      .post(`/stores/${storeId}/write`)
      .reply(statusCode, responseBody);
  },
  delete: (
    storeId: string,
    tuple: TupleKey,
    basePath = defaultConfiguration.getBasePath(),
  ) => {
    return nock(basePath)
      .post(`/stores/${storeId}/write`)
      .reply(200, {} as Promise<object>);
  },
  read: (
    storeId: string,
    tuple: TupleKey,
    basePath = defaultConfiguration.getBasePath(),
  ) => {
    return nock(basePath)
      .post(`/stores/${storeId}/read`)
      .reply(200, { tuples: [] } as ReadResponse);
  },
  expand: (
    storeId: string,
    tuple: TupleKey,
    basePath = defaultConfiguration.getBasePath(),
  ) => {
    return nock(basePath)
      .post(`/stores/${storeId}/expand`)
      .reply(200, { tree: {} } as ExpandResponse);
  },
  readSingleAuthzModel: (
    storeId: string,
    configId: string,
    basePath = defaultConfiguration.getBasePath(),
  ) => {
    return nock(basePath)
      .get(`/stores/${storeId}/authorization-models/${configId}`)
      .reply(200, {
        authorization_model: { id: "some-id", type_definitions: [] },
      } as AuthorizationModel);
  },
  writeAuthorizationModel: (
    storeId: string,
    configurations: WriteAuthorizationModelRequest,
    basePath = defaultConfiguration.getBasePath(),
  ) => {
    return nock(basePath)
      .post(`/stores/${storeId}/authorization-models`)
      .reply(200, {
        id: "some-new-id",
      } as ReadAuthorizationModelResponse);
  },
  readChanges: (storeId: string, type: string, pageSize: number, contToken: string, basePath = defaultConfiguration.getBasePath()) => {
    return nock(basePath)
      .get(`/stores/${storeId}/changes`)
      .query({
        type,
        page_size: pageSize,
        continuation_token: contToken
      })
      .reply(200, {
        changes: [{
          tuple_key: {
            user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
            relation: "viewer",
            object: "document:roadmap"
          },
          operation: TupleOperation.Write,
          timestamp: "2000-01-01T00:00:00Z"
        }],
        "continuation_token": "eyJwayI6IkxBVEVTVF9OU0NPTkZJR19hdXRoMHN0b3JlIiwic2siOiIxem1qbXF3MWZLZExTcUoyN01MdTdqTjh0cWgifQ=="
      } as ReadChangesResponse);
  },
  listObjects: (storeId: string, responseBody: ListObjectsResponse, basePath = defaultConfiguration.getBasePath()) => {
    return nock(basePath)
      .post(`/stores/${storeId}/list-objects`)
      .reply(200, responseBody);
  },
};

describe("Auth0Fga SDK", function () {
  describe("Environment Configurations", () => {
    it("should be able to parse the environment configurations", () => {
      expect(
        () => Configuration.environmentConfigurations
      ).not.toThrowError();
    });

    it("should be able to parse the environment configurations", () => {
      const config = Configuration.getEnvironmentConfiguration("playground");
      expect(config).toMatchObject({
        apiScheme: "https",
        apiHost: "api.playground.fga.dev",
      });
    });
  });

  describe("initializing the sdk", () => {
    it("should require storeId in configuration", () => {
      expect(
        () => new Auth0FgaApi({ ...baseConfig, storeId: undefined! })
      ).toThrowError();
    });

    it("should allow not passing in an environment in configuration", () => {
      expect(
        () => new Auth0FgaApi({ ...baseConfig, environment: undefined! })
      ).not.toThrowError();
    });

    it("should require a valid environment in configuration", () => {
      expect(
        () =>
          new Auth0FgaApi({
            ...baseConfig,
            environment: "non_existent_environment"!,
          })
      ).toThrowError();
    });

    it("should not require clientId or clientSecret in configuration in environments that don't require it", () => {
      expect(
        () =>
          new Auth0FgaApi({
            storeId: AUTH0_FGA_STORE_ID,
            environment: "playground",
            clientId: undefined!,
            clientSecret: undefined!,
          })
      ).not.toThrowError();
    });

    it("should require clientId or clientSecret in configuration in environments that require it", () => {
      expect(
        () =>
          new Auth0FgaApi({
            storeId: AUTH0_FGA_STORE_ID,
            environment: "staging",
            clientId: undefined!,
            clientSecret: undefined!,
          })
      ).toThrowError();
    });

    it("should issue a network call to get the token at the first request if client id is provided", async () => {
      const scope = nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER);
      nocks.readAuthorizationModels(baseConfig.storeId!);

      const fgaApi = new Auth0FgaApi(baseConfig);
      expect(scope.isDone()).toBe(false);

      await fgaApi.readAuthorizationModels();

      expect(scope.isDone()).toBe(true);

      nock.cleanAll();
    });

    it("should cache the bearer token and not issue a network call to get the token at the second request", async () => {
      let scope = nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER);
      nocks.readAuthorizationModels(baseConfig.storeId!);

      const fgaApi = new Auth0FgaApi(baseConfig);
      expect(scope.isDone()).toBe(false);

      await fgaApi.readAuthorizationModels();

      expect(scope.isDone()).toBe(true);

      nock.cleanAll();
      scope = nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER);
      nocks.readAuthorizationModels(baseConfig.storeId!);
      expect(scope.isDone()).toBe(false);

      await fgaApi.readAuthorizationModels();

      expect(scope.isDone()).toBe(false);

      nock.cleanAll();
    });

    it("should not issue a network call to get the token at the first request if the clientId is not provided", async () => {
      const scope = nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER);
      nocks.readAuthorizationModels(baseConfig.storeId!);

      const fgaApi = new Auth0FgaApi({
        ...baseConfig,
        clientId: undefined!,
        clientSecret: undefined!
      });
      expect(scope.isDone()).toBe(false);

      await fgaApi.readAuthorizationModels();

      expect(scope.isDone()).toBe(false);

      nock.cleanAll();
    });

    it("should allow passing in a configuration instance", async () => {
      const configuration = new Configuration(baseConfig);
      expect(() => new Auth0FgaApi(configuration)).not.toThrowError();
    });
  });

  describe("error handling", () => {
    let fgaApi: Auth0FgaApi;
    const { storeId } = baseConfig;
    const basePath = defaultConfiguration.getBasePath();
    const requestId = "1F2A3B";

    beforeAll(() => {
      fgaApi = new Auth0FgaApi({ ...baseConfig });
    });

    describe("400 level error should result in FgaApiValidationError", () => {
      const tupleKey = {
        object: "foobar:x",
        user: "user:xyz",
      };

      beforeEach(async () => {
        nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER, "test-token");

        nock(basePath)
          .defaultReplyHeaders({
            "Fga-Request-Id": requestId,
            "Content-Type": "application/json",
          })
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .reply(400, {
            code: "validation_error",
            message: "nock error",
          });
      });

      afterEach(() => {
        nock.cleanAll();
      });

      it("should throw FgaApiValidationError", async () => {
        await expect(
          fgaApi.check({ tuple_key: tupleKey })
        ).rejects.toThrow(FgaApiValidationError);
      });

      it("FgaApiValidationError should have correct fields", async () => {
        try {
          await fgaApi.check({ tuple_key: tupleKey });
        } catch (err) {
          expect(err).toBeInstanceOf(FgaApiValidationError);
          if (err instanceof FgaApiValidationError) {
            expect(err.apiErrorCode).toBe(ErrorCode.ValidationError);
            expect(err.storeId).toBe(storeId);
            expect(err.endpointCategory).toBe("check");
            expect(err.requestId).toBe(requestId);
          }
        }
      });
    });

    describe("429 level error should result in FgaApiRateLimitExceededError", () => {
      const tupleKey = {
        object: "foobar:x",
        user: "user:xyz",
      };

      beforeEach(async () => {
        const updateBaseConfig = {
          ...baseConfig,
          retryParams: GetDefaultRetryParams(2, 10),
        };
        fgaApi = new Auth0FgaApi({ ...updateBaseConfig });
        nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER, "test-token");

        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .times(3)
          .reply(429, {
            code: "rate_limit_exceeded",
            message: "nock error",
          });
      });

      afterEach(() => {
        nock.cleanAll();
      });

      it("should throw FgaApiRateLimitExceededError", async () => {
        await expect(
          fgaApi.check({ tuple_key: tupleKey }, {})
        ).rejects.toThrow(FgaApiRateLimitExceededError);
      });
    });

    describe("429 with retry in config and retry is successful", () => {
      const tupleKey = {
        object: "foobar:x",
        user: "user:xyz",
      };

      beforeEach(async () => {
        const updateBaseConfig = {
          ...baseConfig,
          retryParams: GetDefaultRetryParams(2, 10),
        };
        fgaApi = new Auth0FgaApi({ ...updateBaseConfig });

        nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER, "test-token");

        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .times(1)
          .reply(429, {
            code: "rate_limit_exceeded",
            message: "nock error",
          });

        nocks.check(baseConfig.storeId!, tupleKey);
      });

      afterEach(() => {
        nock.cleanAll();
      });

      it("should return allowed", async () => {
        const result = await fgaApi.check({ tuple_key: tupleKey, authorization_model_id: "1uHxCSuTP0VKPYSnkq1pbb1jeZw"}, {});

        expect(result.allowed).toBe(true);
      });
    });

    describe("429 with retry in call and retry is successful", () => {
      const tupleKey = {
        object: "foobar:x",
        user: "user:xyz",
      };

      beforeEach(async () => {
        nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER, "test-token");

        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .times(1)
          .reply(429, {
            code: "rate_limit_exceeded",
            message: "nock error",
          });

        nocks.check(baseConfig.storeId!, tupleKey);
      });

      afterEach(() => {
        nock.cleanAll();
      });

      it("should return allowed", async () => {
        const result = await fgaApi.check(
          { tuple_key: tupleKey },
          { retryParams: GetDefaultRetryParams(2, 10) }
        );

        expect(result.allowed).toBe(true);
      });
    });

    describe("500 level error should result in FgaApiInternalError", () => {
      const tupleKey = {
        object: "foobar:x",
        user: "user:xyz",
      };

      beforeEach(async () => {
        nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER, "test-token");
      });

      afterEach(() => {
        nock.cleanAll();
      });

      it("should throw FgaApiInternalError if retries disabled", async () => {
        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .reply(500, {
            code: "internal_error",
            message: "nock error",
          });

        await expect(
          fgaApi.check({ tuple_key: tupleKey }, { retryParams: { maxRetry: 0 }})
        ).rejects.toThrow(FgaApiInternalError);
      });

      it("should not throw FgaApiInternalError with default retries", async () => {
        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .reply(500, {
            code: "internal_error",
            message: "nock error",
          });

        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .reply(200, {
            allowed: true,
          });

        const response = await fgaApi.check({ tuple_key: tupleKey });
        expect(response.allowed).toBe(true);
      });
    });

    describe("404 level error should result in FgaApiNotFoundError", () => {
      const tupleKey = {
        object: "foobar:x",
        user: "user:xyz",
      };

      beforeEach(async () => {
        nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER, "test-token");

        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .reply(404, {
            code: "undefined_endpoint",
            message: "nock error",
          });
      });

      afterEach(() => {
        nock.cleanAll();
      });

      it("should throw FgaApiNotFoundError", async () => {
        await expect(
          fgaApi.check({ tuple_key: tupleKey })
        ).rejects.toThrow(FgaApiNotFoundError);
      });
    });

    describe("401 during authentication should result in FgaApiAuthenticationError", () => {
      const tupleKey = {
        object: "foobar:x",
        user: "user:xyz",
      };

      beforeEach(async () => {
        nock(`https://${ AUTH0_FGA_API_TOKEN_ISSUER}`)
          .post("/oauth/token")
          .reply(401);

        nock(basePath)
          .post(
            `/stores/${storeId}/check`,
            {
              tuple_key: tupleKey,
            },
            expect.objectContaining({ Authorization: "Bearer test-token" })
          )
          .reply(500, {
            code: "invalid_claims",
            message: "nock error",
          });
      });

      afterEach(() => {
        nock.cleanAll();
      });

      it("should throw FgaApiAuthenticationError", async () => {
        fgaApi = new Auth0FgaApi({ ...baseConfig });
        await expect(
          fgaApi.check({ tuple_key: tupleKey })
        ).rejects.toThrow(FgaApiAuthenticationError);
      });
    });
  });

  describe("happy path of CHECK", () => {
    let result: CallResult<CheckResponse>;
    let fgaApi: Auth0FgaApi;

    beforeAll(async () => {
      fgaApi = new Auth0FgaApi({ ...baseConfig });
      nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER);

      const tupleKey = {
        user: "user:xyz",
        relation: "abc",
        object: "foobar:x",
      };
      const scope = nocks.check(baseConfig.storeId!, tupleKey);
      expect(scope.isDone()).toBe(false);

      result = await fgaApi.check({ tuple_key: tupleKey });
      expect(scope.isDone()).toBe(true);

      nock.cleanAll();
    });

    it("should return allowed", () => {
      expect(result.allowed).toBe(true);
    });

    it("should return the proper $response object", () => {
      expect(result).toHaveProperty("$response");
      expect(result.$response.status).toBe(200);
      expect(
        Object.prototype.propertyIsEnumerable.call(result, "$response")
      ).toBe(false);
    });
  });


  describe("using the sdk", () => {
    let fgaApi: Auth0FgaApi;

    beforeAll(() => {
      fgaApi = new Auth0FgaApi({ ...baseConfig });
    });

    beforeEach(() => {
      nocks.tokenExchange(AUTH0_FGA_API_TOKEN_ISSUER);
    });

    afterEach(() => {
      nock.cleanAll();
    });

    describe("check", () => {
      it("should properly pass the request and return an allowed API response", async () => {
        const tuple = {
          user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
          relation: "admin",
          object: "workspace:1",
        };
        const scope = nocks.check(baseConfig.storeId!, tuple);

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.check({ tuple_key: tuple });

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({ allowed: expect.any(Boolean) });
      });
    });

    describe("write: write tuples", () => {
      it("should properly call the Auth0Fga Write API", async () => {
        const tuple = {
          user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
          relation: "admin",
          object: "workspace:1",
        };
        const scope = nocks.write(baseConfig.storeId!);

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.write({
          writes: { tuple_keys: [tuple] },
          authorization_model_id: "1uHxCSuTP0VKPYSnkq1pbb1jeZw",
        });

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({});
      });
    });

    describe("write: delete tuples", () => {
      it("should properly call the Auth0Fga Write API", async () => {
        const tuple = {
          user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
          relation: "admin",
          object: "workspace:1",
        };
        const scope = nocks.delete(baseConfig.storeId!, tuple);

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.write({
          deletes: { tuple_keys: [tuple] },
          authorization_model_id: "1uHxCSuTP0VKPYSnkq1pbb1jeZw",
        });

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({});
      });
    });

    describe("expand", () => {
      it("should properly call the Auth0Fga Expand API", async () => {
        const tuple = {
          user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
          relation: "admin",
          object: "workspace:1",
        };
        const scope = nocks.expand(baseConfig.storeId!, tuple);

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.expand({ tuple_key: tuple, authorization_model_id: "1uHxCSuTP0VKPYSnkq1pbb1jeZw"});

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({});
      });
    });

    describe("read", () => {
      it("should properly call the Auth0Fga Read API", async () => {
        const tuple = {
          user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
          relation: "admin",
          object: "workspace:1",
        };
        const scope = nocks.read(baseConfig.storeId!, tuple);

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.read({ tuple_key: tuple });

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({});
      });
    });

    describe("writeAuthorizationModel", () => {
      it("should call the api and return the response", async () => {
        const authorizationModel = {
          type_definitions: [
            { type: "workspace", relations: { admin: { this: {} } } },
          ],
        };
        const scope = nocks.writeAuthorizationModel(
          baseConfig.storeId!,
          authorizationModel
        );

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.writeAuthorizationModel(
          authorizationModel
        );

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({ id: expect.any(String) });
      });
    });

    describe("readAuthorizationModel", () => {
      it("should call the api and return the response", async () => {
        const configId = "string";
        const scope = nocks.readSingleAuthzModel(baseConfig.storeId!, configId);

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.readAuthorizationModel(configId);

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({
          authorization_model: {
            id: expect.any(String),
            type_definitions: expect.arrayContaining([]),
          },
        });
      });
    });

    describe("readAuthorizationModels", () => {
      it("should call the api and return the response", async () => {
        const scope = nocks.readAuthorizationModels(baseConfig.storeId!, defaultConfiguration.getBasePath(), [{ id: "1", type_definitions: []}]);

        expect(scope.isDone()).toBe(false);
        const data = await fgaApi.readAuthorizationModels();

        expect(scope.isDone()).toBe(true);
        expect(data).toMatchObject({
          authorization_models: expect.arrayContaining([{ id: "1", type_definitions: []}]),
        });
      });
    });

    describe("readChanges", () => {
      it("should call the api and return the response", async () => {
        const type = "repo";
        const pageSize = 25;
        const continuationToken = "eyJwayI6IkxBVEVTVF9OU0NPTkZJR19hdXRoMHN0b3JlIiwic2siOiIxem1qbXF3MWZLZExTcUoyN01MdTdqTjh0cWgifQ==";

        const scope = nocks.readChanges(baseConfig.storeId!, type, pageSize, continuationToken);

        expect(scope.isDone()).toBe(false);
        const response = await fgaApi.readChanges(type, pageSize, continuationToken);

        expect(scope.isDone()).toBe(true);
        expect(response).toMatchObject({ changes: expect.arrayContaining([]) });
      });
    });

    describe("listObjects", () => {
      it("should call the api and return the response", async () => {
        const mockedResponse = { objects: ["document:roadmap"] };
        const scope = nocks.listObjects(baseConfig.storeId!, mockedResponse);

        expect(scope.isDone()).toBe(false);
        const response = await fgaApi.listObjects({
          authorization_model_id: "01GAHCE4YVKPQEKZQHT2R89MQV",
          user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
          relation: "can_read",
          type: "document",
          contextual_tuples: {
            tuple_keys:
              [{
                user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
                relation: "editor",
                object: "folder:product"
              }, {
                user: "folder:product",
                relation: "parent",
                object: "document:roadmap"
              }]
          }
        });

        expect(scope.isDone()).toBe(true);
        expect(response.objects).toHaveLength(mockedResponse.objects.length);
        expect(response.objects).toEqual(expect.arrayContaining(mockedResponse.objects));
      });
    });
  });
});
