/**
 * JavaScript and Node.js SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */

import { Configuration, UserConfigurationParams } from "../../configuration";

export const FGA_ENVIRONMENT = "playground";
export const FGA_STORE_ID = "01H0H015178Y2V4CX10C2KGHF4";
export const FGA_API_HOST = "api.fga.example";
export const FGA_API_TOKEN_ISSUER = "tokenissuer.fga.example";
export const FGA_API_AUDIENCE = "https://api.fga.example/";
export const FGA_CLIENT_ID = "01H0H3D8TD07EWAQHXY9BWJG3V";
export const FGA_CLIENT_SECRET = "this-is-very-secret";

export const baseConfig: UserConfigurationParams = {
  storeId: FGA_STORE_ID,
  environment: FGA_ENVIRONMENT,
  clientId: FGA_CLIENT_ID,
  clientSecret: FGA_CLIENT_SECRET,
};

export const defaultConfiguration = new Configuration(baseConfig);
